name: Build
env:
  # The name Apk
  apk_name: Hea
  
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      #Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      #Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew        
      
      # Build APK
      - name: Build with Gradle
        run: ./gradlew build
      
      # Create APK Debug
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug
      
      # Upload Artifact Build
      # Noted For Output app/build/outputs/apk/debug/
      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.apk_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: app/build/outputs/apk/debug/
